author: Valentin Knabel
author_url: https://twitter.com/vknabel
github_url: https://github.com/vknabel/SwiftHook
module: SwiftHook
module_version: 2.0.0
root_url: https://vknabel.github.io/SwiftHook/
readme: README.md
output: docs/
theme: fullwidth
